# Site Settings
title: bholaCodeCamp
description: "Welcome to BholaCodeCamp — where I’m leveling up my technical knowledge and inviting you to read the blogs. With cool tutorials, handy dev resources, and an awesome blogs, we’re all about learning, building, and having fun."
baseurl: "/bholacodecamp"
url: "https://rajeshbhola.github.io/"
permalink: /:title/

# Author Info
author:
  name: Rajesh Bhola
  bio: Fullstack Developer and Technical Blog Writer

# Social Links
social:
  twitter: therajeshbhola
  github: rajeshbhola?tab=repositories
  youtube: bholacodecamp

# Build Settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
paginate: 6
paginate_path: "/page:num/"


# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Analytics
google_analytics: UA-XXXXXXXX-X

# Compression
sass:
  style: compressed

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md